// === KuzuDB Schema Types ===

export type CodeNodeType = "file" | "function" | "class" | "method";

export interface FileNode {
  id: string;
  name: string;
  filePath: string;
  summary: string; // what this file does (~50 tokens, generated by Agent 4)
  relevance: number; // structural importance 0.0–1.0, auto-computed from in/out degree
}

export interface FunctionNode {
  id: string;
  name: string;
  filePath: string;
  startLine?: number;
  endLine?: number;
  summary: string; // what this function does (~50 tokens, generated by Agent 4)
  relevance: number; // structural importance 0.0–1.0, auto-computed from in/out degree
}

export interface ClassNode {
  id: string;
  name: string;
  filePath: string;
  summary: string; // what this class does (~50 tokens, generated by Agent 4)
  relevance: number; // structural importance 0.0–1.0, auto-computed from in/out degree
}

// Person nodes: invisible infrastructure in KuzuDB (not rendered by default)
export interface PersonNode {
  id: string;
  name: string;
  email: string;
}

// Relationship types — progressive disclosure (L1/L2/L3) lives here, not on nodes

export interface ContributedRel {
  // Core metrics (from git log)
  commits: number;
  lastTouch: string;
  linesChanged: number;
  // Ownership (from git blame)
  blameLines: number; // lines currently attributed to this person
  ownershipPct: number; // % of current lines owned
  // Progressive disclosure
  summary_l1: string; // "Alice: 14 commits, owns 73% of current lines, last Jan 2026"
  commits_json: string; // JSON array of per-commit details (L2)
}

export interface UnderstandsRel {
  confidence: "deep" | "surface" | "none";
  source: "quiz" | "voice_interview" | "git" | "inferred";
  topics: string[];
  lastAssessed: string;
  needsRetest: boolean; // true when node has new commits since last assessment
  // Progressive disclosure
  summary_l1: string; // "Alice: deep — edge cases, rate limiting, token refresh"
  sessions_json: string; // JSON array of per-interview-session results (L2)
}

// Discussion node: stores voice interaction transcripts (linked via HAS_PARTICIPANT + ABOUT edges)
export interface DiscussionNode {
  id: string;
  timestamp: string;
  transcript: string;
  summary_l1: string; // brief summary of what was discussed
  quizResult?: string; // 'correct' | 'incorrect' if quiz-related
  confidenceBefore?: string;
  confidenceAfter?: string;
}

export interface HasParticipantRel {
  role: string; // 'interviewer' | 'interviewee'
}

export interface AboutRel {
  focus?: string; // e.g. 'implementation', 'architecture', 'bug'
}

// === Overlay Modes ===

export type OverlayMode = "structure" | "contributors" | "knowledge" | "people";
// structure:     code nodes only, colored by type (file/fn/class), edges = CALLS/IMPORTS
// contributors:  code nodes colored/sized by contributor activity, filter by person
// knowledge:     code nodes colored by knowledge coverage (green=deep, red=gap), filter by person
// people:        Person nodes become visible, showing human topology around code clusters

// === Visualization Types (derived from KuzuDB for react-force-graph) ===

export interface VizNode {
  id: string;
  name: string;
  type: CodeNodeType | "person"; // 'person' only visible in people overlay
  filePath?: string;
  val?: number;
  color?: string;
  // Metadata attached for display (from KuzuDB queries per overlay mode)
  contributors?: { person: string; commits: number }[];
  knowledgeScore?: number;
  summary?: string;
}

export interface VizLink {
  source: string;
  target: string;
  type: "contains" | "calls" | "imports" | "inherits" | "contributed" | "understands";
  color?: string;
}

export interface GraphData {
  nodes: VizNode[];
  links: VizLink[];
}
